// <auto-generated />
using System;
using DataCodeFirst.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataCodeFirst.Migrations
{
    [DbContext(typeof(Lab1DBContext))]
    [Migration("20210518063805_adddbwithFluent")]
    partial class adddbwithFluent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataCodeFirst.Entities.ChucVu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaCV")
                        .HasColumnType("int");

                    b.Property<string>("TenCV")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.CuaHang", b =>
                {
                    b.Property<int>("CuaHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DicchiCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDTrangThai")
                        .HasColumnType("int");

                    b.Property<int>("MaCH")
                        .HasColumnType("int");

                    b.Property<string>("TenCh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThanhPho")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CuaHangID");

                    b.ToTable("CuaHang");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.DongSanPham", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDTRANGTHAI")
                        .HasColumnType("int");

                    b.Property<int>("MADSP")
                        .HasColumnType("int");

                    b.Property<string>("TENDSP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("DongSanPham");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDTrangThai")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<int>("MaHD")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhanHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayShipHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoHD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThanhToanHD")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.HoaDonChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("DONGIA")
                        .HasColumnType("real");

                    b.Property<int?>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("SOLUONG")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("SanPhamID");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDTrangThai")
                        .HasColumnType("int");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("Macty")
                        .HasColumnType("int");

                    b.Property<int>("Mst")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDemKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tencty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhPho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sodt")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.NhanVien", b =>
                {
                    b.Property<int>("NhanVienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChucVuId")
                        .HasColumnType("int");

                    b.Property<int>("CuaHangId")
                        .HasColumnType("int");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<int>("IDTrangThai")
                        .HasColumnType("int");

                    b.Property<float>("LuongNV")
                        .HasColumnType("real");

                    b.Property<int>("MaNv")
                        .HasColumnType("int");

                    b.Property<int>("Sodt")
                        .HasColumnType("int");

                    b.Property<string>("TenDemNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NhanVienID");

                    b.HasIndex("ChucVuId");

                    b.HasIndex("CuaHangId");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.PhieuBaoHanh", b =>
                {
                    b.Property<int>("PhieuBaoHanhID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<int>("IDTRANGTHAI")
                        .HasColumnType("int");

                    b.Property<int>("IMEI")
                        .HasColumnType("int");

                    b.Property<string>("MOTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NGAYBATDAU")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NGAYKETTHUC")
                        .HasColumnType("datetime2");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.HasKey("PhieuBaoHanhID");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("PhieuBaoHanh");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.SanPham", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DongSanPhamId")
                        .HasColumnType("int");

                    b.Property<float>("GIABAN")
                        .HasColumnType("real");

                    b.Property<float>("GIANHAP")
                        .HasColumnType("real");

                    b.Property<int>("IDTRANGTHAI")
                        .HasColumnType("int");

                    b.Property<int>("MAHINH")
                        .HasColumnType("int");

                    b.Property<int>("MASP")
                        .HasColumnType("int");

                    b.Property<string>("MOTA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SOLUONG")
                        .HasColumnType("int");

                    b.Property<string>("TENSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TRONGLUONGSP")
                        .HasColumnType("real");

                    b.Property<int>("ThuongHieuId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DongSanPhamId");

                    b.HasIndex("ThuongHieuId");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.ThuongHieu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDTRANGTHAI")
                        .HasColumnType("int");

                    b.Property<int>("MATH")
                        .HasColumnType("int");

                    b.Property<string>("TENTH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WEBSITE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ThuongHieu");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.HoaDon", b =>
                {
                    b.HasOne("DataCodeFirst.Entities.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataCodeFirst.Entities.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.HoaDonChiTiet", b =>
                {
                    b.HasOne("DataCodeFirst.Entities.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonID");

                    b.HasOne("DataCodeFirst.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamID");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.NhanVien", b =>
                {
                    b.HasOne("DataCodeFirst.Entities.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("ChucVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataCodeFirst.Entities.CuaHang", "CuaHang")
                        .WithMany("NhanViens")
                        .HasForeignKey("CuaHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("CuaHang");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.PhieuBaoHanh", b =>
                {
                    b.HasOne("DataCodeFirst.Entities.HoaDon", "HoaDon")
                        .WithMany("PhieuBaoHanhs")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataCodeFirst.Entities.SanPham", "SanPham")
                        .WithMany("PhieuBaoHanhs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.SanPham", b =>
                {
                    b.HasOne("DataCodeFirst.Entities.DongSanPham", "DongSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("DongSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataCodeFirst.Entities.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("ThuongHieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DongSanPham");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.CuaHang", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.DongSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.HoaDon", b =>
                {
                    b.Navigation("PhieuBaoHanhs");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.SanPham", b =>
                {
                    b.Navigation("PhieuBaoHanhs");
                });

            modelBuilder.Entity("DataCodeFirst.Entities.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
